# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mobile Threat Catalogue

# site.baseurl wasn't expanding correctly in the link, which is why /mobile-threat-catalogue
# is hardcoded.
description: >
    <p>
        In order to fully address the inherent threats of mobile devices,
        a wider view of the mobile ecosystem is necessary. This repository
        contains the Mobile Threat Catalogue, which describes, identifies, and
        structures the threats posed to mobile information systems. The <a href="/mobile-threat-catalogue/background.html">background</a> page
        provides context and a description of the origins of this repository.
    </p>
    <p>
      Readers of the catalogue may notice
      threats that are not tied to a documented source or lack countermeasures,
      and other threats may exist that are not identified here. This catalogue is
      intended as a living document. Though the initial comment period is now closed,
      feedback on mobile threats addressed in
      the catalogue as well as ideas for additional threats are still encouraged.
    </p>


baseurl: "/mobile-threat-catalogue" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov" # the base hostname & protocol for your site
#twitter_username: jekyllrb

# Build settings
exclude: [vendor]
markdown: kramdown
sass:
    sass_dir: _sass

collections:
    application-threats:
        output: true
    authentication-threats:
        output: true
    stack-threats:
        output: true
    cellular-threats:
        output: true
    ecosystem-threats:
        output: true
    emm-threats:
        output: true
    gps-threats:
        output: true
    lan-pan-threats:
        output: true
    payment-threats:
        output: true
    physical-threats:
        output: true
    privacy-threats:
        output: true
    supply-chain-threats:
        output: true
    background:
        output: true

defaults:
  - scope:
      type: application-threats
    values:
      merged: true
  - scope:
      type: authentication-threats
    values:
      merged: true
  - scope:
      type: stack-threats
    values:
      merged: true
  - scope:
      type: cellular-threats
    values:
      merged: true
  - scope:
      type: ecosystem-threats
    values:
      merged: true
  - scope:
      type: emm-threats
    values:
      merged: true
  - scope:
      type: gps-threats
    values:
      merged: true
  - scope:
      type: lan-pan-threats
    values:
      merged: true
  - scope:
      type: payment-threats
    values:
      merged: true
  - scope:
      type: physical-threats
    values:
      merged: true
  - scope:
      type: privacy-threats
    values:
      merged: true
  - scope:
      type: supply-chain-threats
    values:
      merged: true
  - scope:
      type: background
    values:
      merged: true
